include(joinpath("dataProcessing", "anomalies.jl"))
include(joinpath("dataProcessing", "causeSelection.jl"))
include(joinpath("dataProcessing", "dataSelection.jl"))
include(joinpath("dataProcessing", "processOverflow.jl"))
include(joinpath("dataProcessing", "siteSelection.jl"))